#config for ehp
[ehp]

    [ehp.horizon]
    # denote whether the horizon extend strategy is enabled in parking scenario
    horizon_extend_in_parking_scenario_required = false

    # denote the least distance for the horizon extend strategy in parking scenario
    horizon_extend_in_parking_scenerio_least_distance = 10.0

    # denote the straight on angle threshold in horizon extend strategy, in degree
    horizon_extend_straight_on_angle_threshold = 20.0

    # denote the range of the horizon data: distance forward with current location
    horizon_data_range_forward_search_distance = 7000

    # denote the range of the horizon data: distance backward with current location
    horizon_data_range_backward_search_distance = 500

    # denote the range of the horizon data: search distance for off route
    horizon_data_range_off_route_search_distance = 200

    # denote the range of the horizon data: car-side required distance range
    horizon_data_range_required_distance = 5000

    # denote the minimum vehicle moving distance to change the horizon
    minimum_distance_to_change_horizon_data = 0.3

    # denote the horizon msg frequency
    horizon_msg_frequency_hz = 10

    # send horizon msg or not while the car is off the route
    send_horizon_msg_while_off_route = false

    # denote the threshold of ddmap frequency max limit 
    horizon_msg_hz_ddmap = 1000

    # denote the frequency of the tour info topic by hz
    tour_info_hz = 1

    # denote whether send tour info or not
    enable_tour_info = true

    [ehp.routing]

    # denote the angle threshold between two travelable roads in junction,
    # telling whether routing can travel from one road to another.
    routing_road_connection_turn_angle_threshold = 3.15

    # denote the extra cost for u-turn road in routing module
    routing_uturn_extra_cost = 80

    # denote the extra cost for intersection left turn road in routing module
    routing_intersection_left_turn_extra_cost = 50

    # denote whether the file of traverse route for parking is required.
    traverse_route_for_parking_from_file_required = false

    # denote the allowable reversing range when calculating route
    routing_allowable_reversing_range = 20

    #denote the sparse threshold of routing points, higher to get less points
    routing_points_sparse_threshold = 0.1

    # denote the distance extended the front of route
    routing_extend_forward_distance = 0

    # denote the distance extended the rear of route
    routing_extend_backward_distance = 0

    # denote the distance calculate the trun angle between linked roads
    routing_turn_angle_calculate_distance_threshold = 15

    # denote the tour list length threshold
    sd_match_tour_list_length_ = 1

    [ehp.update_manager]

    use_update_manager = false

    # denote catalog name
    catalog_name = "mix_new_mdm_release"

    # denote mpp api host
    mpp_host = "https://hdmap.momenta.cn/mpp"

    # denote auth api host
    auth_host = "https://hdmap.momenta.cn/account-server"

    # denote sd match service api host
    sd_match_host = "https://hdmap.momenta.cn"

    #denote sd match service api path
    sd_match_path =  "/cupid/api/v1/sdmap-match-hdmap"

    # denote auth username
    auth_username = "admin_mpp"

    # denote auth password
    auth_password = "Y1aP3$CNML9Qb298"

    # denote tiles
    tiles = "all"

    # denote versions
    versions = "2"

    [ehp.offroutegenerate]
    # the threshold of mpp generate distance in off_route mode
    off_route_mpp_generate_distance_threshold = 500

    [ehp.dataaccess]
    # use zht sdk interface switch, true: ON; false: OFF
    zhtsdk_on_off = false 
    # zht sdk db absolute path
    zhtsdk_db_path = ""
    # mdm init load db mode, true:load all tile into cache; false:load one tile into cache
    mdm_init_all_load = true

    is_parking_scenario = false

    hdmap_version_topic_frequency_hz = 0.033

    # remove elevation in mdm data
    mdm_force_zero_elevation = false

[ehp.task]
# 9999 means invalid
# low frequency infomation thread priority
ehp_low_frequency_thread_priority = 9999
# hd road match thread priority
ehp_road_match_thread_priority = 9999
# dd map thread_priority
ehp_dd_map_thread_priority = 9999
# running core
ehp_running_core = 9999
# ehp hdmap init
ehp_hdmap_init = true
# ehp ddmap init
ehp_ddmap_init = false

[ehp.nodestatus]
node_status_topic_frequency_hz = 10

#config for ehr
[ehr]

    [ehr.lane_path]
    #determine if lane_path is calculated or feeded
    lane_path_feeded = false

    #determine if bus_stop and no-parking-area affect lane path calculation
    bus_stop_affect_lane_path = true

    no_parking_area_affect_lane_path = true

    [ehr.referenceline]
    # generate refline when update lane path or not
    use_refline = true

    # interpolation length
    interpolation_len = 2.0

    # the number of referencelines(current, left side and right side)
    hd_refline_num = 5

    dd_refline_num = 3

    hd_refline_calc_use_cache = true

    dd_refline_calc_use_cache = false

    hd_refline_cache_width = 10 # 100(m->cm)/(grid_size in cm)

    dd_refline_cache_width = 10 # 100(m->cm)/(grid_size in cm)

    hd_refline_cache_size = 3000

    dd_refline_cache_size = 3000

    # the forward range of referenceline(meters)
    refline_forward_distance = 300

    # the backward range of referenceline(meters)
    refline_backward_distance = 50

    use_experience_trajectory = false

    use_experience_guidance_line = true

    [ehr.task]
    # 9999 means invalid
    # low frequency infomation thread priority
    ehr_low_frequency_thread_priority = 9999
    # ha map thread priority
    ehr_hd_map_thread_priority = 9999
    # dd map thread_priority
    ehr_dd_map_thread_priority = 9999
    # running core
    ehr_running_core = 9999

#config for ehp and ehr
[common]

    # map matching section
    [common.map_matching]

    # denote whether the matching strategy takes the lane path into account.
    prefer_lane_path = true

    # denote Yaw threshold when doing map matching for the current vehicle
    theta_threshold = 1

    # denote distance threshold when doing map matching for the current vehicle
    distance_threshold = 9

    # Check whether the mdm data have no divergent area compiled.
    data_have_no_divergent_area = false

    # denote the forward offset to create the reachable area
    reachable_area_forward_offset = 50

    # denote the backward offset to create the reachable area
    reachable_area_backward_offset = 5

    # denote the lat threshold enter parking space
    match_in_parking_space_lat_threshold_input = 2

    # denote the long threshold enter parking space
    match_in_parking_space_long_threshold_input = 3

    # denote the lat threshold go away parking space
    match_in_parking_space_lat_threshold_output = 4

    # denote the long threshold go away parking space
    match_in_parking_space_long_threshold_output = 6

    # denote the distance between vehicle rear and center
    match_by_scenarios_vehicle_rear_to_center_distance = 1.2

    # denote the distance threshold when destination reached
    match_by_scenarios_destination_reached_threshold = 0.4

    # denote the switch of vehicle state off route destination reached
    match_by_scenarios_destination_reached_switch = false

    # denote the distance threshold run away from last lane path
    run_away_from_lane_path_threshold = 1.5

    # denote the hysteresis threshold from last lane path to current lane
    hysteresis_threshold_from_lane_path_to_cur_lane = 0

    #denote the distance from rear axle to front
    vehicle_rear_axle_to_front_distance = 3.8

    #denote the road match(match lane by road) distance threshold for graphposmatcher
    road_match_to_lane_distance_threshold = 20

    [common.madapter]

    # denote whether the lane level navi info is required.
    lane_level_info_required = true

    # denote searching distance when preparing guidance data
    horizon_attribute_search_distance = 30000

    # denote if horizon kit uses global coordiante: false = local, true = global
    horizon_use_global_coordinate = false

    [common.elevation]
    # denote whether mapmatching or search takes elevation input into account
    elevation_filter_required = false

    # denote the error threshold when taking elevation input into account
    elevation_threshold = 0.5

    [common.search]
    # denote distance threshold when searching parking lot
    parking_distance_threshold = 0.5

    # denote angle threshold when searching parking lot
    parking_angle_threshold = 0.174

    [common.log]
    # denode lowest visible log level
    level = "info"

    dump_horizon_binary = false

    dump_horizon_binary_path_ehp = "/home/ros/Downloads/dump_ehp/"

    dump_horizon_binary_path_ehr = "/home/ros/Downloads/dump_ehr/"

    [common.horizonmode]

    # denote if hdmap is enabled
    horizon_enable_hdmap = true

    # denote if ddmap is enabled
    horizon_enable_ddmap = false

    [common.topviewlog]
    #denote whether to output topview log or not
    topview_log_output_online = false

    topview_log_output_offline = false
