param_version: multi_circle_footprint_model_v1.1
type: S450L
circle_num: 23
#body (circle0 && circle 6 are also for rear && front bumper)
circle0:
  x: -0.1
  y: 0
  r: 0.977
circle1:
  x: 0.44
  y: 0
  r: 0.955
circle2:
  x: 0.98
  y: 0
  r: 0.955
circle3:
  x: 1.51
  y: 0
  r: 0.965
circle4:
  x: 2.05
  y: 0
  r: 0.97
circle5:
  x: 2.59
  y: 0
  r: 0.97
circle6:
  x: 3.113
  y: 0
  r: 0.977

#rear bumper
circle7:
  x: -0.685
  y: 0.425
  r: 0.5
circle8:
  x: -0.4
  y: 0.16
  r: 0.8
circle9:
  x: -0.685
  y: -0.425
  r: 0.5
circle10:
  x: -0.4
  y: -0.16
  r: 0.8

#front bumper
circle11:
  x: 3.51
  y: 0.42
  r: 0.53
circle12:
  x: 3.51
  y: -0.42
  r: 0.53

#mirror
circle13:
  x: 2.08
  y: 0.93
  r: 0.13

circle14:
  x: 2.08
  y: -0.93
  r: 0.13

#wheels
circle15:
  x: -0.15
  y: 0.81
  r: 0.16

circle16:
  x: 0.15
  y: 0.81
  r: 0.16

circle17:
  x: -0.15
  y: -0.81
  r: 0.16

circle18:
  x: 0.15
  y: -0.81
  r: 0.16

circle19:
  x: 3.07
  y: 0.80
  r: 0.16

circle20:
  x: 3.37
  y: 0.80
  r: 0.16

circle21:
  x: 3.07
  y: -0.80
  r: 0.16

circle22:
  x: 3.37
  y: -0.80
  r: 0.16


# footprint model  definition
# each footprint is defined as a combination of multiple circles
#    if include model(s) is(are) defined, include circles will be added to it
#    include model can only be models above
#    include and parent model must be the same height
#    only one include model supported in this version(for performance)

# model_num is fixed in 3, can't change in this version
# each layer description is also fixed, don't change


#height descriptions see :SbpObstacleHeightType:


model_num: 3
#### 0. the low height footprint model. height 0 ~ bumper_height
model0: 
  height: "LOW"
  include_model: []
  index: [15, 16, 17, 18, 19, 20, 21, 22]
  description: "low_wheels"

#### 1. the not_allow_close footprint model. left&&right edge
model1:
  height: "HIGH"
  include_model: []
  index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
  description: "not_allow_close"

#### 2. the full-size footprint model. as in top-view footprint model
model2:
  height: "HIGH"
  include_model: [1]
  index: []
  description: "full_body"
