# syntax=docker/dockerfile:experimental
ARG IMAGE_FPP=artifactory.momenta.works/docker-momenta/np_planning/fpp:maf3.2.1-5

FROM ${IMAGE_FPP}

RUN apt install -y \
    libbz2-dev \
    liblz4-dev \
    libconsole-bridge-dev \
    clang-format-6.0 \
    libgoogle-perftools-dev \
    libffi-dev \
    linux-tools-generic \
    tzdata

RUN cd /opt && git clone https://github.com/brendangregg/FlameGraph.git

RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple numpy protobuf==3.12 jupyter bokeh jupytext pybind11 yep ipywidgets scipy pandas easydict pycryptodome pycryptodomex gnupg docutils pyparsing
RUN pip3 install --extra-index-url https://rospypi.github.io/simple/ rospy rosbag roslz4

RUN chmod -R 777 /root
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN touch /.ccache_remote_flag && chmod 777 /.ccache_remote_flag

ENV RUN_IN_BUILD_ENV=TRUE \
    MF_SYSTEM_ROOT_DIR=/root/modo_mf_system \
    DOCKER_TAG_ID=fpp \
    BUILD_ENV_ID=fpp \
    PROJ_NAME=FPP \
    MFS_SYSTEM_CFG_YAML=config/Fpp/system3.0.yaml \
    _MCOMPILE_EXTRA_FLAGS_="-g -O2 -Wfatal-errors -fstack-protector-all -z noexecstack -Wl,--build-id=sha1" \
    CUDA_VISIBLE_DEVICES=0 \
    TZ="Asia/Shanghai" \
    RUN_IN_FPP_CONTAINER=TRUE \
    HOME=/root

ENTRYPOINT []
