footprint_model: # types: "point", "circular", "two_circles", "line", "polygon", "three_circles"
    type: "four_circles"
    radius: 1.0 # for type "circular"
    line_start: [0.0, 0.0] # for type "line"
    line_end: [2.85, 0.0] # for type "line"
    front_offset_three_circles: 3.12 # for type "two_circles""three_circles"
    front_radius_three_circles: 1.20 # for type "two_circles""three_circles"
    rear_offset_three_circles: 0.343 # for type "two_circles""three_circles"
    rear_radius_three_circles: 1.2 # for type "two_circles""three_circles"
    middle_offset_three_circles: 1.0735 # for type "three_circles"
    middle_radius_three_circles: 1.2 # for type "three_circles"

    front_offset_four_circles: 3.0 # for type "four_circles"
    front_radius_four_circles: 1.0 # for type "four_circles"
    middle_front_offset_four_circles: 2.2 # for type "four_circles"
    middle_front_radius_four_circles: 1.06 # for type "four_circles"
    middle_rear_offset_four_circles: 0.8 # for type "four_circles"
    middle_rear_radius_four_circles: 1.0 # for type "four_circles"
    rear_offset_four_circles: 0.2 # for type "four_circles"
    rear_radius_four_circles: 0.95 # for type "four_circles"

    vertices: [ [-1.0, 1.0], [3.85, 1.0], [3.85, -1.0], [-1.0, -1.0] ] # for type "polygon"
