OBSTACLE_AVOID_PARAM:  
  default_swell_distance: 5.0
  default_step_size: 5.0
  min_obstacle_dist: 0.8
  min_static_obstacle_dist_default: 0.5
  physics_border_offset_default: -0.3
  virtual_border_offset_default: 0.0
  pillar_offset_default: -0.3
  couple_offset_default: 0.0
  ped_offset_default: 0.0
  freespace_offset_default: 0.0
  lead_offset_default: -0.3
  l_range_hack: 1.6
  min_obstacle_dist_addition: 0.15
  min_obstacle_dist_factor: 1.2
  min_obstacle_dist_max: 0.8
  min_obstacle_dist_min: 0.4
  min_obstacle_dist_entrance: 0.4
  couple_offset_factor: 1.2
  couple_offset_min: -0.3
  min_static_obstacle_dist_min: 0.3
  min_static_obstacle_dist_offset: -0.3
  min_virtual_obstacle_dist_check_upper_bound: 0.3
  min_free_obstacle_dist_check_upper_bound: 0.3
  min_obstacle_dist_check_upper_bound: 0.4
  min_fix_obstacle_dist_check_lower_bound: 0.3
  couple_offset_max: -0.05
  couple_offset_attenuation: 1.2
  pillar_offset_min: -0.3
  pillar_offset_max: -0.15
  pillar_offset_attenuation: 0.7
  pillar_offset_factor: 1.1
  pillar_offset_offset: -0.3
  pillar_offset_l_range_min: -0.3
  lead_offset_max: -0.01
  lead_offset_min: -0.3
  lead_offset_l_range_offset: -0.3
  couple_offset_interf_addition: -0.2

TRAGECTORY_GENERATOR_PARAM:
  default_distance: 20.0
  end_s_add_default: 5.0
  off_track_l_limit: 1.5
  end_s_add_off_track: 8.0
  distance_length_addition_default: 12.0
  distance_length_left_left_addition: 8.0
  turn_start_curv_limit: 0.2
  turn_end_curv_limit: 0.1
  end_s_cutoff_offset: 0.5
  length_upper_check_offset: 2.0
  goal_generate_after_turn_offset: 4.0
  target_effective_check_s_step: 1.0
  target_effective_max_curv: 0.05
  target_effective_count: 3
  target_effective_end_s_offset: 3.0
  target_effective_box_collision_limit: 0.1



