VIA_WEIGHT_PARAM:
  VIA_WEIGHT_LANE:
    - 0.5
    - 0.5
    - 1.2 
    - 3.0 
    - 8.0
  VIA_WEIGHT_LANE_INTERSECTION:
    - 0.5
    - 0.5
    - 0.96
    - 1.5
    - 4.0

  VIA_WEIGHT_DISTANCE:
    - 0.0
    - 1.0
    - 1.5
    - 1.0
    - 2.0

  VIA_WEIGHT_EGO:
    - 2.0
    - 0.8
    - 0.65
    - 0.5
    - 0.5

  WEIGHT_VIA_BASE_INTERSECTION: 4.0
  WEIGHT_VIA_BASE_LANE: 8.0
  interf_dist_limit: 1.0
  off_track_l_limit: 1.5
  clip_off_track_l_min: 0.0
  clip_off_track_l_max: 2.0
  weight_factor: 1.05
  via_traj_lookahead_time: 2.0
  distance_ahead_min: 0.3
  front_via_limit_range: 10.0

VIA_ADD_PARAM:
  curve_theta_check_limit: 0.78539816339745
  long_lane_min: 12.0
  double_lane_border_distance: 1.0
  avg_curvature_limit: 0.10
  straight_lane_length_before_limit: 6.0
  straight_lane_length_after_limit: 6.0
  road_width_middle_min: 6.0
  road_width_middle_max: 7.5
  turn_width_diff_limit: -1.0
  double_lane_length_middle_max: 15.0
  double_lane_length_middle_min: 6.0
  curve_lane_point_curv_max: 0.10
  curve_lane_point_curv_mmin: 0.03
  ref_trajectory_info_via_delta_s_filter: 0.5
  epsilon: 0.01
  check_turn_delta_s: 0.4
  check_turn_pt_count: 10
  check_turn_pt_invalid_limit: 4




