#!/bin/bash

export MFR_IP="127.0.0.1"

PWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )/" && pwd -P )"
export MODULE_ROOT_DIR=$PWD
export LOG_ROOT="${MODULE_ROOT_DIR}/output/log/maf_planning"

LIB_DIR=${MODULE_ROOT_DIR}/lib

MODULE_LIB_DIR=${MODULE_ROOT_DIR}/lib
DEPENDS_LIB_DIR=${MODULE_LIB_DIR}/depends
DEPENDS_LIB_DIR2=${MODULE_LIB_DIR}/depends/lib
MFR_LIB_DIR=${MODULE_LIB_DIR}/depends/mfr_lib/lib
CORE_LIB_DIR=${MODULE_LIB_DIR}

export APA_PLANNING_MFR_LIBRARY=${MODULE_LIB_DIR}/libplanning_mfr_node.so
export SBP_MFR_LIBRARY=${MODULE_LIB_DIR}/libsbp_mfr_node.so
export LD_LIBRARY_PATH=${MODULE_ROOT_DIR}:${MFR_LIB_DIR}:${MODULE_LIB_DIR}:${DEPENDS_LIB_DIR}:${DEPENDS_LIB_DIR2}:${CORE_LIB_DIR}
export SBP_PLANNING_RESOURCE_PATH=${MODULE_ROOT_DIR}/resource
export APA_PLANNING_RESOURCE_PATH=${MODULE_ROOT_DIR}/resource
export APA_PLANNING_SCENE_TYPE=0

mkdir -p ${LOG_ROOT}