# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - pr/trigger
      - cpp/main
      - cpp/main-dev-apa
      - release/apa/v1.4.9
      - sop/lacar/v6.43_cpp
      - cpp_main_space_slot
      - release/apa/ygg/main_wls_apa_1212

pool:
  name: default
jobs:
- job: PNC_APA_Evaluation
  timeoutInMinutes: 240
  steps:
  - script: sh start_open_loop.sh
    displayName: PNC-APA评测
    failOnStderr: true
    env:
      target_branch: $(System.PullRequest.TargetBranch)
      source_branch: $(System.PullRequest.SourceBranch)
      main_commit: $(Build.SourceVersion)
      user_name: $(Build.RequestedFor)
      task_name: $(Agent.JobName)
      trigger_type: $(Build.Reason)

      build_directory: $(Build.Repository.LocalPath)
      branch: $(Build.SourceBranchName)
      pr_id: $(System.PullRequest.PullRequestId)
      pr_commit_id: $(System.PullRequest.SourceCommitId)
    condition: eq(variables['Build.Reason'], 'PullRequest')