# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
# trigger:
#   branches:
#     include:
#       #- FX/pipeline_test
#       - cpp/main_ddp_temp_tsj
      

pool:
  name: default

resources:
  containers:
  - container: cmake_with_cuda_torch_ros3
    endpoint: artifactory
    image: artifactory.momenta.works/docker-momenta/build_env_devcar_momenta_cmake_with_cuda_torch_ros3:v0.0.2

schedules:
- cron: "00 16 * * *"
  displayName: timing triger
  branches:
    include:
    - FX/pipeline_test


jobs:
- job: check_simulation_function
  workspace:
    clean:
      all
  timeoutInMinutes: 180
  pool:
    name: 'default'
  steps:
  - checkout: self
    clean: true
    lfs: false
    submodules: recursive
    persistCredentials: true
  - bash: |
      bash .ci/$(Agent.JobName).sh
    displayName: $(Agent.JobName)
    env:
      offboard_branch: wgz/submit_cisim
      user_name: $(Build.RequestedFor)
      ci_type: $(Build.Reason)
      Onboard_commit: $(Onboard_commit)
      pr_id: $(System.PullRequest.PullRequestId)
      build_directory: $(Build.Repository.LocalPath)
      pr_email: $(Build.RequestedForEmail)
      
  - task: PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()

#- job: check_consistency
#  workspace:
#    clean:
#      all
#  steps:
#  - checkout: self
#    clean: true
#    lfs: false
#    submodules: recursive
#    persistCredentials: true
#
#  - bash: |
#      bash .ci/$(Agent.JobName).sh
#    displayName: $(Agent.JobName)
#    env:
#      base_commit: $(npp_base_commit)
#      offboard_branch: $(npp_offboard_branch)
#
#  - task: PostBuildCleanup@3
#    displayName: 'Clean Agent Directories'
#    condition: always()




