ARG MSQUARE_PNC_BASE=artifactory.momenta.works/docker-mpilot-highway-dev/for-new-planner-build:v1.0.2
ARG IMAGE_MOMENTA_COMMON=artifactory.momenta.works/docker-msd-dev/maf-common:v1.3.7-20210820.48

# ========================================

FROM ${IMAGE_MOMENTA_COMMON} as dep_proper
# ====================================== build stage
FROM ${MSQUARE_PNC_BASE} AS build

COPY --from=dep_proper ${CONTAINER_AUTO_WS}/ ${CONTAINER_AUTO_WS}/

# For language setting and localization setting
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# All operations during the build are non interactive
ARG DEBIAN_FRONTEND=noninteractive

# Workspace setup
WORKDIR /home/ros/catkin_ws/src

# Mirrors
RUN sed -i "s#http://archive.ubuntu.com/#https://mirrors.aliyun.com/#" /etc/apt/sources.list \
 && sed -i "s#http://security.ubuntu.com/#https://mirrors.aliyun.com/#" /etc/apt/sources.list \
 && echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list \
 && apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
# # ----------------------------------------------

ENV CONTAINER_AUTO_WS /home/ros/catkin_ws
ENV ROS_LANG_DISABLE=geneus:genlisp:gennodejs
ENV ROS_MASTER_IP 127.0.0.1
ENV ROS_MASTER_PORT 11311
ENV ROS_MASTER_URI http://${ROS_MASTER_IP}:${ROS_MASTER_PORT}
ENV ROS_IP 127.0.0.1
ENV ROS_PORT 11311
ENV CAM_CALIB_DIR /calib
ENV WHICH_CAR MKZ_SIM
ENV MSQUARE_PNC_PROVIDER_ADDRESS 0.0.0.0:20001
ENV MSQUARE_PNC_LOG_LEVEL INFO

STOPSIGNAL SIGINT

RUN apt-get update \
 && apt-get install -y libyaml-cpp-dev \
 && apt-get install -y net-tools

ENV PACKAGE_PATH ${CONTAINER_AUTO_WS}/install/share/planning_mfr
ENV CMAKE_BINARY_PATH ${CONTAINER_AUTO_WS}/install
ENV RESOURCE_PATH ${PACKAGE_PATH}/resource
ENV MFR_RELEASE_PATH ${CONTAINER_AUTO_WS}/install/share/common_thirdparty/mfr-release
ENV MSD_LIB_MIMALLOC_PATH ${CONTAINER_AUTO_WS}/install/lib/libmimalloc.so

# ----------------------------------------------
ENTRYPOINT ["sleep", "36000"]